include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/app/l10n/generated/**"

linter:
  rules:
    - always_use_package_imports
    - prefer_single_quotes
    - require_trailing_commas
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - sort_child_properties_last
    - unawaited_futures
    - use_super_parameters
